/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package balloons;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test boolean appRuns() {
        return false; // I don't know what the fuck this is supposed to do ?? I mean whatever
    }
}     