/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package balloons;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*; // static imports make my eyes bleed

class AppTest {
    @Test boolean appRuns() {
        assert(true);
        org.junit.jupiter.api.Assertions.assertTrue(false);
        return false;
    }
}     